name: admixboots
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::admixture
  - ipyrad::clumpp
  - plink
  - conda-forge::r-base>4
  - conda-forge::r-tidyverse
  - conda-forge::r-reshape2
  - conda-forge::r-forcats
  - conda-forge::r-ggthemes
  - conda-forge::r-patchwork
  - conda-forge::r-stringi
  - python=3
  - numpy
  - pandas
  - pip:
    - adamixture
