name: admixboots
channels:
  - conda-forge
  - bioconda
dependencies:
  - admixture=1.3.0
  - ipyrad::clumpp=1.1.2
  - plink=1.90b4
  - conda-forge::r-base>4
  - conda-forge::r-tidyverse
  - conda-forge::r-reshape2
  - conda-forge::r-forcats
  - conda-forge::r-ggthemes
  - conda-forge::r-patchwork
  - conda-forge::r-stringi
  - python=3
  - numpy
  - pandas
