name: admixboots
channels:
  - bioconda
  - conda-forge
  - defaults
  - r
dependencies:
  - admixture=1.3.0
  - ipyrad::clumpp=1.1.2
  - plink=1.90b4
  - r-base>4
  - r-tidyverse
  - r-reshape2
  - r-forcats
  - r-ggthemes
  - r-patchwork
  - python=3
  - numpy
  - pandas
